name:                quenched-polymer
version:             0.1.0.0
github:              "Illmir/quenched-polymer"
license:             BSD-3-Clause
author:              "Benjamín Pavez Ortega"
maintainer:          "bipavez.o@gmail.com"
copyright:           "2025 Benjamín Pavez Ortega"

extra-source-files:
- README.md
- CHANGELOG.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/Illmir/quenched-polymer#readme>

# The library section
library:
  source-dirs: src
  exposed-modules:
    - Lib
  dependencies:
    - base >= 4.14
    - monad-bayes
    - numeric-log
    - cassava

# The executable section
executables:
  my-ising-proj-exe:
    main: Main.hs
    source-dirs: app
    ghc-options:
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
    dependencies:
      - my-ising-proj

# We typically don't want to build tests/benchmarks that might pull in `vty`/unix
tests:    {}
benchmarks: {}